backend:
  name: github
  repo: drhasib/GYO # উদাহরণ: drhasib/my-project
  branch: main # আপনার মেইন ব্রাঞ্চের নাম

media_folder: "images/uploads" # ছবি আপলোড করলে যেখানে সেভ হবে
public_folder: "/images/uploads"

collections:
  - name: "blog" # কালেকশনের নাম
    label: "Blog Post" # ড্যাশবোর্ডে যা দেখাবে
    folder: "content/blog" # যেখানে পোস্টগুলো সেভ হবে
    create: true # নতুন পোস্ট ক্রিয়েট করার অপশন
    fields: # পোস্টের ভেতরে কী কী ডাটা থাকবে
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
